<div class="row">
	<div class="col-lg-12">
		<div class="pane-heading" style="margin-top: 30px;"><h4>Respuesta</h4></div>
	</div>
</div>	
<div class="row">
	<div class="col-lg-12">
			<section class="panel" style="margin-top:10px;">
                <header class="panel-heading bg-light lter">
                  <ul class="nav nav-tabs">
                    <li><a href="#get_client_level1_description_tab1" data-toggle="tab"> Modelo</a></li>
                    <li  class="active"><a href="#get_client_level1_description_tab2" data-toggle="tab"> Esquema</a></li>
                  </ul>
                </header>
                <div class="panel-body">
                  <div class="tab-content">              
                   	<div class="tab-pane" id="get_client_level1_description_tab1">
                   		<div class="row">
                   			<div class="col-lg-12">...</div>	
                   		</div>
                   	</div>
                    <div class="tab-pane active" id="get_client_level1_description_tab2">
                    	<div>{ </div>
		                    	<div>"status": "success",</div>
		                    	<div>"client":  </div>
		                    	<div style="overflow: hidden;padding-left:30px;">
		                    			<div>[ </div>
				                   	 	<div>{ </div>	
				                   	 		<div style="padding-left:10px;"><strong>"idclient"</strong>: 1,</div>
				                   	 		<div style="padding-left:10px;"><strong>"client_name"</strong>: "Gustavo Salazar Soria",</div>
				                   	 		<div style="padding-left:10px;"><strong>"client_email"</strong>: "g.s@hostdime.com",</div>
				                   	 		<div style="padding-left:10px;"><strong>"client_email2"</strong>: "gus.salazar@icloud.com",</div>
				                   	 		<div style="padding-left:10px;"><strong>"client_phone"</strong>: "3316026459",</div>
				                   	 		<div style="padding-left:10px;"><strong>"client_cellular"</strong>: "3316023939"</div>
				                    	<div>}, </div>	
				                    	<div>{ </div>	
				                   	 		<div style="padding-left:10px;"><strong>"idclient"</strong>: 2,</div>
				                   	 		<div style="padding-left:10px;"><strong>"client_name"</strong>: "Carlos Esparza",</div>
				                   	 		<div style="padding-left:10px;"><strong>"client_email"</strong>: "carlos.i@hostdime.com.mx",</div>
				                   	 		<div style="padding-left:10px;"><strong>"client_email2"</strong>: "carlos.esparza.i@hotmail.com",</div>
				                   	 		<div style="padding-left:10px;"><strong>"client_phone"</strong>: "3316026429",</div>
				                   	 		<div style="padding-left:10px;"><strong>"client_cellular"</strong>: "3312326429"</div>
				                    	<div>} </div>	
				                    	<div>] </div>
				               </div>     	
                    	<div>}</div>
                   	</div>
                   
                  </div>
                </div>
              </section>		
	</div>
</div>
<div class="row">
	<div class="col-lg-12">
		<div class="pane-heading" style="margin-top: 30px;"><h4>Códigos de error</h4></div>
	</div>
</div>	
<div class="row">
	<div class="col-lg-12">
		<section class="panel" style="margin-top: 10px;">
                    <table class="table table-striped m-b-none text-sm">
                      <thead>
                      		<tr>
                      			<th style="width: 40px;">Error</th>
                      			<th>Descripción</th>
                      			<th style="width: 60px;"></th>
                      		</tr>
                      </thead>
                      <tbody>
                      		<tr>
                      			<td>404</td>
                      			<td>Entidad no encontrada</td>
                      			<td>
                      				<a href="#comment-form" class="btn btn-white btn-xs">
			                            <i class="fa fa-external-link text-muted"></i> Esquema
			                          </a>
                      			</td>
                      		</tr>
                      		<tr>
                      			<td>500</td>
                      			<td>Error Interno</td>
                      			<td>
                      				<a href="#comment-form" class="btn btn-white btn-xs">
			                            <i class="fa fa-external-link text-muted"></i> Esquema
			                          </a>
                      			</td>
                      		</tr>
                      </tbody>
                    </table>
		</section>    
	</div>
</div>