<div class="row">
		<div class="col-lg-12">
			<div class="panel-group m-b" id="levels_getclient">
				<!-- level1 -->
                <div class="panel">
	                  <div class="panel-heading">
	                    <a class="accordion-toggle" data-toggle="collapse" data-parent="levels_getclient" href="#get_client_level1">
	                      <i class="fa fa-ellipsis-v"></i> Nivel 1
	                    </a>
	                  </div>
	                  <div id="get_client_level1" class="panel-collapse collapse">
	                    <div class="panel-body text-sm">
	                    	<?php echo $this->render("/documentation/index/company/client/get_client/levels/1.phtml"); ?>
	                    </div>
	                  </div>
               	</div>
               	<!-- /level1 -->
               	<!-- level2 -->
               	<div class="panel">
	                  <div class="panel-heading">
	                    <a class="accordion-toggle" data-toggle="collapse" data-parent="levels_getclient" href="#get_client_level2">
	                      <i class="fa fa-ellipsis-v"></i> Nivel 2
	                    </a>
	                  </div>
	                  <div id="get_client_level2" class="panel-collapse collapse">
	                    <div class="panel-body text-sm">
	                    ---
	                    </div>
	                  </div>
               	</div>
               	<!-- /level2 -->
               	<!-- level3 -->
               	<div class="panel">
	                  <div class="panel-heading">
	                    <a class="accordion-toggle" data-toggle="collapse" data-parent="levels_getclient" href="#get_client_level3">
	                      <i class="fa fa-ellipsis-v"></i> Nivel 3
	                    </a>
	                  </div>
	                  <div id="get_client_level3" class="panel-collapse collapse">
	                    <div class="panel-body text-sm">
	                    ---
	                    </div>
	                  </div>
               	</div>
               	<!-- /level3 -->
               	<!-- level4 -->
               	<div class="panel">
	                  <div class="panel-heading">
	                    <a class="accordion-toggle" data-toggle="collapse" data-parent="levels_getclient" href="#get_client_level4">
	                      <i class="fa fa-ellipsis-v"></i> Nivel 4
	                    </a>
	                  </div>
	                  <div id="get_client_level4" class="panel-collapse collapse">
	                    <div class="panel-body text-sm">
	                    ---
	                    </div>
	                  </div>
               	</div>
               	<!-- /level4 -->
               	<!-- level5 -->
               	<div class="panel">
	                  <div class="panel-heading">
	                    <a class="accordion-toggle" data-toggle="collapse" data-parent="levels_getclient" href="#get_client_level5">
	                      <i class="fa fa-ellipsis-v"></i> Nivel 5
	                    </a>
	                  </div>
	                  <div id="get_client_level5" class="panel-collapse collapse">
	                    <div class="panel-body text-sm">
	                    ---
	                    </div>
	                  </div>
               	</div>
               	<!-- /level5 -->
            </div>
       </div>
</div>               	
                    