<div class="wrapper">
	<div class="row">
		<div class="col-lg-12">
		 	<h1 class="font-thin"> <strong class="font-bold text-success">RESTService</strong> </h1>
	        <div class="panel-body">
                        <blockquote>
                          <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer posuere erat a ante.</p>
                          <small>Someone famous in <cite title="Source Title">Source Title</cite></small>
                        </blockquote>
            </div>                      
	    </div>    
	</div>
	<?php echo $this->render("/documentation/index/modules.phtml");?>
</div>	