<div class="row">
		<div class="col-lg-12">
			<div class="panel-group m-b" id="accordion_modules">
				<!-- company -->
                <div class="panel">
	                  <div class="panel-heading">
	                    <a class="accordion-toggle" data-toggle="collapse" data-parent="accordion_modules" href="#module_company">
	                      <i class="fa fa-ellipsis-v"></i> Compañia
	                    </a>
	                  </div>
	                  <div id="module_company" class="panel-collapse collapse">
	                    <div class="panel-body text-sm">
	                    	<?php echo $this->render("/documentation/index/company/submodules.phtml"); ?>
	                    </div>
	                  </div>
               	</div>
               	<!-- /company -->
               	<!-- sales -->
               	<div class="panel">
	                  <div class="panel-heading">
	                    <a class="accordion-toggle" data-toggle="collapse" data-parent="accordion_modules" href="#module_sales">
	                      <i class="fa fa-ellipsis-v"></i> Sales
	                    </a>
	                  </div>
	                  <div id="module_sales" class="panel-collapse collapse">
	                    <div class="panel-body text-sm">
	                    ---
	                    </div>
	                  </div>
               	</div>
               	<!-- /sales -->
            </div>
       </div>
</div>               	
                    