<div class="row">
		<div class="col-lg-12">
			<div class="panel-group m-b" id="resource_client">
				<!-- get_client -->
                <div class="panel">
	                  <div class="panel-heading">
	                    <a class="accordion-toggle" data-toggle="collapse" data-parent="resource_client" href="#get_client">
	                      	<span class="badge bg-info">GET</span>  <span style="margin-left: 10px;"> /company/clients</span>
	                    </a>
	                  </div>
	                  <div id="get_client" class="panel-collapse collapse">
	                    <div class="panel-body text-sm">
	                    	<?php echo $this->render("/documentation/index/company/client/get_client/levels.phtml");?>
	                    </div>
	                  </div>
               	</div>
               	<!-- /get_client -->
               	<!-- post_client -->
               	<div class="panel">
	                  <div class="panel-heading">
	                    <a class="accordion-toggle" data-toggle="collapse" data-parent="resource_client" href="#post_client">
	                     <span class="badge bg-success">POST</span>  <span style="margin-left: 10px;"> /company/clients</span>
	                    </a>
	                  </div>
	                  <div id="post_client" class="panel-collapse collapse">
	                    <div class="panel-body text-sm">
	                    ---
	                    </div>
	                  </div>
               	</div>
               	<!-- /post_client -->
            </div>
       </div>
</div>               	
                    