<div class="row">
		<div class="col-lg-12">
			<div class="panel-group m-b" id="submodule_company">
				<!-- client -->
                <div class="panel">
	                  <div class="panel-heading">
	                    <a class="accordion-toggle" data-toggle="collapse" data-parent="submodule_company" href="#service_client">
	                      <i class="fa fa-ellipsis-v"></i> Cliente
	                    </a>
	                  </div>
	                  <div id="service_client" class="panel-collapse collapse">
	                    <div class="panel-body text-sm">
	                    	<?php echo $this->render("/documentation/index/company/client/resources.phtml");?>
	                    </div>
	                  </div>
               	</div>
               	<!-- /client -->
               	<!-- branch -->
               	<div class="panel">
	                  <div class="panel-heading">
	                    <a class="accordion-toggle" data-toggle="collapse" data-parent="submodule_company" href="#service_branch">
	                      <i class="fa fa-ellipsis-v"></i> Sucursal
	                    </a>
	                  </div>
	                  <div id="service_branch" class="panel-collapse collapse">
	                    <div class="panel-body text-sm">
	                    ---
	                    </div>
	                  </div>
               	</div>
               	<!-- /branch -->
            </div>
       </div>
</div>               	
                    